blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Hyggshi-OS-project-center/nexcode-ide/wiki
    about: Check the wiki for documentation
  - name: Discussions
    url: https://github.com/Hyggshi-OS-project-center/nexcode-ide/discussions
    about: Ask questions and discuss ideas with the community