name: Build NexCode IDE (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Windows app
        shell: bash
        run: |
          ./scripts/build-app-all-Windows.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: NexCode-IDE-Windows
<<<<<<< HEAD
          path: dist/pack-out/*.exe   # ← output dir theo electron-builder.config
=======
          path: dist/pack-out/*.exe
>>>>>>> a761327 (feat: add custom tab scrollbar with drag support and multi-platform build scripts)
          retention-days: 7
